script: echo whee
notifications:
  webhooks:
    urls:
    - 'https://webhook-staging.atomist.services/travis'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
